module Ffccmmx
  class HTTPXRetryableError < HTTPX::Error
    attr_reader response: HTTPX::Response

    def self.retryable_error?:(HTTPX::Error) -> bool

    def retry_time:(?count: Integer) -> Time
  end
end
