module Ffccmmx
  VERSION: String

  def self.build: (String, ?base_url:  String, ?topic_base_url:  String)-> Client
  def self.new: (String, ?base_url: String, ?topic_base_url: String)-> Client

  def self.configuration: () -> Configuration
  def self.reset_configuration: () -> Configuration
  def self.configure: () { (Configuration) -> void } -> void
end
